# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86a344696242c0bccc4ce0b145a1355a5f81642475249579edefc3963517f40f3559b92546ac768f8f2f51d763e0dc68bf8ca6f322bc1bfc1897835b8ef0aab3

test:
  secret_key_base: 10ee975221325850200480ed9cf97bc49c186308b39f7b64fdb890b82cf811752406b49a8e7183689de295c60557f05cfca37320649c2d0c0cdb773f7ce3147b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
